### ISSUE TITLE
can you backport this?

### ISSUE THREAD

**Issue by RYUKxAnime** [SoRadGaming/simple-utilities-mod#2]
the UI location configuring would be very helpful
please if you can backport this to 1.17.1 fabric
its okay if you cant

**Comment by SoRadGaming** [comment]
I'll check and see

**Comment by SoRadGaming** [comment]
I might just recode the plugin from scratch, and setup an automated system to create the mod for multiple versions, and also create a forge page. Considering the original mod maker is no longer maintaining the plugin.

**Comment by xerone69** [comment]
anytime soon?

**Comment by SoRadGaming** [comment]
Yes, I have rewritten the plugin from scratch, making it much more modular (easy to maintain) and adding new features; just getting issues with modmenu fixed, and a multiversion staging system (including 1.17 compatible version). I would say 2 more weeks (also planning for 1.18, 1.17, 1.16 compatibility).

Note: Was busy with otherstuff, only started 2 days ago and its like 60% done

**Comment by SoRadGaming** [comment]
Finished the rewrite, and here's the release. (No armour Hud because I can't be bothered)

https://github.com/SoRadGaming/Simple-HUD-Enhanced/releases/tag/v1.0.0

https://legacy.curseforge.com/minecraft/mc-mods/simple-hud-enhanced
